export const animeData = [
  {
    title: "Satoshi Rike",
    description:
      "A young ninja seeks recognition from his peers and dreams of becoming the Hokage.",
    genre: "Action, Adventure",
    likes: 1000,
    rating: 9,
    starred: 500,
    liked_by: [],
    starred_by: [],
    comments: [],
    thumbnail_url:
      "https://res.cloudinary.com/dponzgerb/image/upload/v1728726323/bdnvc1ewa7e7o0ueqgdt.jpg",
    stream_url: "http://localhost:8080/output.m3u8",
    is_live: true,
  },
  {
    title: "One Piece",
    description:
      "A young pirate embarks on a journey to find the greatest treasure in the world.",
    genre: "Adventure, Fantasy",
    likes: 1200,
    rating: 9.5,
    starred: 800,
    liked_by: [],
    starred_by: [],
    comments: [],
    thumbnail_url:
      "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=1200,height=675/catalog/crunchyroll/a249096c7812deb8c3c2c907173f3774.jpg",
    stream_url: "http://localhost:8080/output.m3u8",
    is_live: false,
  },
  {
    title: "Attack on Titan",
    description: "Humans fight for survival against terrifying titans.",
    genre: "Action, Fantasy",
    likes: 900,
    rating: 9.3,
    starred: 600,
    liked_by: [],
    starred_by: [],
    comments: [],
    thumbnail_url:
      "https://a.storyblok.com/f/178900/1920x1080/efdffb9f1d/attack-on-titan-final-season-levi.png",
    stream_url: "http://localhost:8080/output.m3u8",
    is_live: false,
  },
  {
    title: "Dragon Ball Z",
    description: "Goku and his friends protect Earth from powerful enemies.",
    genre: "Action, Adventure",
    likes: 1500,
    rating: 8.8,
    starred: 700,
    liked_by: [],
    starred_by: [],
    comments: [],
    thumbnail_url:
      "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=1200,height=675/catalog/crunchyroll/36bdc5ea4443cd8e42f22ec7d3884cbb.jpg",
    stream_url: "http://localhost:8080/output.m3u8",
    is_live: false,
  },

  {
    title: "Hunter x Hunter",
    description:
      "A boy searches for his father and embarks on a journey to become a Hunter.",
    genre: "Adventure, Fantasy",
    likes: 1400,
    rating: 9.0,
    starred: 650,
    liked_by: [],
    starred_by: [],
    comments: [],
    thumbnail_url:
      "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=1200,height=675/catalog/crunchyroll/2e54344c7cc1675af721b4021222230f.jpg",
    stream_url: "http://localhost:8080/output.m3u8",
    is_live: false,
  },
  {
    title: "Bleach",
    description:
      "A teenager gains the powers of a Soul Reaper to protect the world from evil spirits.",
    genre: "Action, Supernatural",
    likes: 1150,
    rating: 8.5,
    starred: 400,
    liked_by: [],
    starred_by: [],
    comments: [],
    thumbnail_url:
      "https://cdn.animenewsnetwork.com/thumbnails/crop900x350/video/category/15/key_art_bleach.jpg",
    stream_url: "http://localhost:8080/output.m3u8",
    is_live: false,
  },
  {
    title: "Fairy Tail",
    description: "A group of powerful wizards embarks on thrilling adventures.",
    genre: "Adventure, Fantasy",
    likes: 1050,
    rating: 8.0,
    starred: 380,
    liked_by: [],
    starred_by: [],
    comments: [],
    thumbnail_url:
      "https://m.media-amazon.com/images/S/pv-target-images/d5d5c77008ec00c46c7ad195c377f76a06abe0822a987d0c890a0ccf1c143f73.jpg",
    stream_url: "http://localhost:8080/output.m3u8",
    is_live: false,
  },
  {
    title: "Black Clover",
    description:
      "A young boy dreams of becoming the Wizard King in a world where magic is everything.",
    genre: "Action, Fantasy",
    likes: 950,
    rating: 7.8,
    starred: 300,
    liked_by: [],
    starred_by: [],
    comments: [],
    thumbnail_url:
      "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=1200,height=675/catalog/crunchyroll/0273e80242d80b0218f640e038269c18.jpg",
    stream_url: "http://localhost:8080/output.m3u8",
    is_live: false,
  },
  {
    title: "Re:Zero - Starting Life in Another World",
    description:
      "A young man is transported to a fantasy world where he must repeat his death over and over.",
    genre: "Adventure, Drama",
    likes: 900,
    rating: 8.3,
    starred: 360,
    liked_by: [],
    starred_by: [],
    comments: [],
    thumbnail_url:
      "https://m.media-amazon.com/images/S/pv-target-images/0559334408c12ef5e0a6a3d5d2df2e22e707c4c5fa8918889c898cf2c2573c11.jpg",
    stream_url: "http://localhost:8080/output.m3u8",
    is_live: false,
  },
  {
    title: "Steins;Gate",
    description:
      "A self-proclaimed mad scientist and his friends discover time travel.",
    genre: "Sci-Fi, Thriller",
    likes: 1000,
    rating: 9.1,
    starred: 500,
    liked_by: [],
    starred_by: [],
    comments: [],
    thumbnail_url:
      "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=1200,height=675/catalog/crunchyroll/ac6e22b27d285ed90e72744584d23434.jpe",
    stream_url: "http://localhost:8080/output.m3u8",
    is_live: false,
  },
  {
    title: "Mob Psycho 100",
    description: "A powerful psychic tries to lead a normal life.",
    genre: "Action, Supernatural",
    likes: 800,
    rating: 8.7,
    starred: 350,
    liked_by: [],
    starred_by: [],
    comments: [],
    thumbnail_url:
      "https://m.media-amazon.com/images/S/pv-target-images/aaa253b7a9f9fb95264c68c31cd04b9030a5d7b0212e1b01d437dc5631c62799._SX1080_FMjpg_.jpg",
    stream_url: "http://localhost:8080/output.m3u8",
    is_live: false,
  },
  {
    title: "Code Geass",
    description:
      "A young man uses the power of Geass to lead a rebellion against an oppressive empire.",
    genre: "Action, Mecha",
    likes: 1100,
    rating: 9.0,
    starred: 450,
    liked_by: [],
    starred_by: [],
    comments: [],
    thumbnail_url:
      "https://m.media-amazon.com/images/S/pv-target-images/f6229414d529451c2677a18db912a09fc8ee78a78669cf7043acbc8d952a6f8c.jpg",
    stream_url: "http://localhost:8080/output.m3u8",
    is_live: false,
  },
  {
    title: "Neon Genesis Evangelion",
    description:
      "A group of teenagers pilot giant mechs to protect Earth from mysterious beings.",
    genre: "Mecha, Psychological",
    likes: 1200,
    rating: 8.9,
    starred: 550,
    liked_by: [],
    starred_by: [],
    comments: [],
    thumbnail_url:
      "https://m.media-amazon.com/images/S/pv-target-images/526c5dcf1dab6d883aacafb6b283acdf9192223b594b836c2abfbe68cd62eda5._UR1920,1080_.jpg",
    stream_url: "http://localhost:8080/output.m3u8",
    is_live: false,
  },
  {
    title: "The Promised Neverland",
    description:
      "A group of children discovers the dark secret behind their orphanage.",
    genre: "Mystery, Thriller",
    likes: 950,
    rating: 8.5,
    starred: 400,
    liked_by: [],
    starred_by: [],
    comments: [],
    thumbnail_url:
      "https://m.media-amazon.com/images/M/MV5BMGQ4ZGJhZTUtZDQ5Mi00NTI1LWEyYjItMzIxM2VlNmY4MDEyXkEyXkFqcGc@._V1_.jpg",
    stream_url: "http://localhost:8080/output.m3u8",
    is_live: false,
  },
];
